version: '3'
services:
  node:
    build: .
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
      - "26656:26656"
    volumes:
      - ${PWD}/heimdall:/root/.heimdalld/:ro
      - ${PWD}/logs:/root/logs:ro
      - ${PWD}/bor:/root/.bor:ro