services:
  node:
    build: .
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
      - "26656:26656"
    volumes:
      - type: volume
        source: logs
        target: /root/logs/
      - type: volume
        source: heimdall
        target: /root/.heimdalld/
      - type: volume
        source: bor
        target: /root/.bor/


volumes:
  heimdall:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: heimdall
  bor:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: bor
  logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: logs