name: Create and publish the coin's containers
on:
  push:
    branches: ['master']
  schedule: 
    - cron: "0 13 11 * *"
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'tag for this image build'
        required: true
        default: 'latest'
    
jobs:
  build-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coins: [bitcoin, litecoin, dogecoin, ethereum, bitcoingold]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: gostartups
          password: ${{ secrets.SECRET }}
      -
        name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          context: "."
          push: true
          tags: gostartups/${ matrix.coins }-core:latest
      - 
        name: Build and push with Tag
        uses: docker/build-push-action@v2
        if: 
          ${{ github.event.input.image_tag != null }}
        with:
          context: "."
          push: true
          tags: gostartups/${ matrix.coins }:${{ github.event.inputs.image_tag }}
